/** @format */
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ClientWrapper from "./ClientWrapper"; // Adjust the import path accordingly
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Weather Monitoring",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ClientWrapper>
        <body className={inter.className}>
          {children}
          <h1 className=" items-center justify-center bg-gray-700 flex text-white w-full p-5  font-semibold">
            &copy;2024. All rights reserved
          </h1>
        </body>
      </ClientWrapper>
    </html>
  );
}
