/** @format */
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ClientWrapper from "./ClientWrapper"; // Adjust the import path accordingly
import { ClerkProvider } from "@clerk/nextjs";
import Home from "./page";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Weather Monitoring",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <ClientWrapper>
          <body className={inter.className}>
            {children}
            <footer className="row-start-3 flex gap-6 flex-wrap items-center justify-center text-white bg-gray-700 h-50 p-5">
              <h3>&copy;2024 All right reserved.</h3>
            </footer>
          </body>
        </ClientWrapper>
      </html>
    </ClerkProvider>
  );
}
